Repository camera-2018/hdu-cs-wiki, pull requests merged in 2023-04, with the labels that each got.

#7 sovle promble with 4.2and4.3.1
  4.人工智能/4.2机器学习（AI）快速入门（quick start）.md
  4.人工智能/4.3.1搜索.md
Labels: 文档问题喵

#19 add Reid
  .vitepress/config.js
  4.人工智能/4.6.5.5行人重识别(ReID).md
  4.人工智能/static/ReID1.png
  4.人工智能/static/ReID2.png
Labels: 好问题喵, 待补充喵

#30 update：add contents of DRL to 4.6.9
  .vitepress/config.js
  4.人工智能/4.6.9.1前言.md
  4.人工智能/4.6.9.2基础资料推荐.md
  4.人工智能/4.6.9深度强化学习.md
Labels: 文档增强喵
